### PR TITLE
upgrade debug tools🛠

### PR DESCRIPTION
**Pull request by makc**
Ok, so this is all editor-related commits since March 29 cherry-picked and combined together. This adds `atlas.debug()`, `atlas.player.showHelpers()`, `controler.permissions.airborne`, teleport button, etc, but I am not even sure this will work right away if merged - but it should - since it might implicitly rely on something in the unrelated commit - but it should not. Proceed at your own risk with extreme caution.

Now the last part remains for me to do - actual terrain editor. I am still thinking about minecraft-ish approach where you could create 5 tiles in one click, but that probably needs tons of code to find connected tiles and so on... I see you have `adjTileExists` there, that might be a start. Well, laterz

### CODE REVIEW

**Comment by felixmariotto** [comment]
OK, given the amount of changes I will take the time to do that carefully.

**Comment by felixmariotto** [comment]
Seriously your debug mod is fantastic ! Being able to add cubes on the fly, tweak walls to make them climbable, it's so much fun while you play. I wish you find a solution for adding tiles !

I will do some more communication on Reddit to talk about the new stuff you did and probably get more traction. Last time there were two people asking for how to contribute. I told them what you're doing and that you would probably use some help, with a link to your fork, but I had no idea that one cannot post an issue on a fork. If somebody else ask me, should I tell them to post an issue on my repo so you can get in touch, or do you prefer to do your things on your own ? I could also add this to the new "Contributing" section of my readme.

**Comment by felixmariotto** [comment]
Also I've done some cleanup commits

**Comment by makc** [comment]
> I had no idea that one cannot post an issue on a fork

I just turned it off when setting it up because I did not think I would be using that feature.

> communication on Reddit

Ah, Ive been wondering where new forks came from

**Comment by makc** [comment]
Btw, here is one spot where the code is broken - https://github.com/felixmariotto/Edelweiss/blob/master/public/js/atlas.js#L1372 - this should be prefixed with your AWS path

**Comment by felixmariotto** [comment]
> Btw, here is one spot where the code is broken - https://github.com/felixmariotto/Edelweiss/blob/master/public/js/atlas.js#L1372 - this should be prefixed with your AWS path

thanks it's fixed

**Pull request merged**
