### PR TITLE
remove unused / broken code

### PR DESCRIPTION
**Pull request by makc**
This one is not really necessary, but it would be nice if you accept - then my fork will stay closer to  yours.

Apart from obviously not used libs (stats, dat gui) and vars, there are 3 major points:

* dynamic items purged from the code that supports some cube animations - it is not used at the moment, but if you will start using it, you will run into problems with multiplayer (where one user triggered the animation but all the others did not); another reason is this simplifies the job for my in-game editor 😉
* development layout and json loading removed - it did not really work at all (I have replaced it with [this](https://github.com/makc/Edelweiss/commit/edff4212bc2e52ba150759ca5c83ea84cb2c9eb4#diff-17be339469992e2d422b1235e44a3434R154-R218) in my fork - but that is beyond this PR);
* orbit controls - they did not follow the player, and even if that was fixed - I dont think it would be really useful.

### CODE REVIEW

**Comment by felixmariotto** [comment]
Ah this dynamic items system... If you knew how big the project was when I started it ! It was basically Zelda, with moving NPCs and pets, side quests... Then I realised how much work it would be (especially the level design and modelling), so I cut it down a lot.

**Comment by felixmariotto** [comment]
I'd really like to merge your map editor when you finish it !

**Comment by makc** [comment]
That would probably be somewhere in the summer. So far, only scaling-moving and removing the cubes is supported. No tiles, no planes.

But I sort of like where it is going, e g you could move the cube and immediately see how the player interacts with it. Or you could edit glb and add then add the cube to match it - the opposite workflow to what you had before.

A day ago I have added 3 lines of code to keep the guy from falling when gliding, so that I could navigate the map easy but still keep the player bahavior exactly as in the game - I have then spent like half an hour just flying around with no clear purpose. Things like that sort of keep it fun for me.

**Comment by felixmariotto** [comment]
It's super exciting, especially if you can try the map in one click after editing !

> A day ago I have added 3 lines of code to keep the girl from falling when gliding, so that I could navigate the map easy but still keep the player bahavior exactly as in the game - I have then spent like half an hour just flying around with no clear purpose. Things like that sort of keep it fun for me.

I was thinking about it, if you let the player fiddle with the map, it may be better to let them choose their powers at start, and maybe add some simple options like tweaking jump height, or as you said making new fun powers like infinite flying or overpowered dash ?

**Comment by makc** [comment]
I still have infinity jump not changed to double jump in my fork, so together with infinite gliding that covers pretty much every navigation need.

**Pull request merged**
